version: "3"

services:
  my-app:
    image: cr.yandex/${REGISTRY_ID}/${REPO}:latest
    # platform: linux/amd64
    build:
      context: .
    environment:
      env_file:
        .env
    ports:
      - "${PORT:-3000}:3000"
    restart: always
    networks:
      - awesome

networks:
  awesome:
    driver: bridge
